# Generated by Django 3.2.20 on 2023-07-28 08:33

import core.models
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_loan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='text',
        ),
        migrations.AddField(
            model_name='loan',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='status',
            field=django_enumfield.db.fields.EnumField(default=0, enum=core.models.LoanStatus),
        ),
        migrations.AddField(
            model_name='loan',
            name='terms',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='ts_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(null=True)),
                ('status', django_enumfield.db.fields.EnumField(default=0, enum=core.models.RepaymentStatus)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='core.loan')),
            ],
        ),
    ]
