# Generated by Django 3.2.20 on 2023-07-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_loan_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='ts_created',
        ),
        migrations.AddField(
            model_name='loan',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='repayment',
            name='due_date',
            field=models.DateField(null=True),
        ),
    ]
